<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h1 class="display-3">Přihlášení -  konference 2020</h1>
                <form action="login"  method="post">
                    <div class = "form-group">
                        <label> Username </label>
                        <input type="text" name="user" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label> Password </label>
                        <input type="password" name="password" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <a href="registrace"> Ještě nemáte účet? Klikněte ZDE </a>
                    </div>
                    <button type="submit" name="submit" class="btn btn-primary"> Login </button>
                </form>
            </div>
        </div>
    </div>
</div>
