
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">Program konference 2020</h1>

        <table class="table">
            <thead>
            <tr>
                <th scope="col">Akce</th>
                <th scope="col">Datum</th>
                <th scope="col">Od-Do</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Přivítání účastníků</td>
                <td>12.12.2020</td>
                <td>14:00-16:00</td>
            </tr>
            <tr>
                <td>Vysvětlení pravidel pro diskuzi</th>
                <td>12.12.2020</td>
                <td>16:00-17:00</td>
            </tr>
            <tr>
                <td>Filmová premiéra dokumentu o ZČU</th>
                <td>12.12.2020</td>
                <td>18:30-20:45</td>
            </tr>
            <tr>
                <td>Slavnostní večeře</th>
                <td>12.12.2020</td>
                <td>21:00-24:00</td>
            </tr>
            <tr>
                <td>Diskuze</th>
                <td>13.12.2020</td>
                <td>11:00-16:00</td>
            </tr>
            <tr>
                <td>Večeře</th>
                <td>13.12.2020</td>
                <td>16:00-17:30</td>
            </tr>
            <tr>
                <td>Doprovodné akce</th>
                <td>14.12.2020</td>
                <td>10:00-16:00</td>
            </tr>
            <tr>
                <td>Volná diskuze, procházení po kampusu</th>
                <td>14.12.2020</td>
                <td>16:00-22:00</td>
            </tr>
            </tbody>
        </table>

    </div>
</div>