<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <div class="col-md-10 ">
            <h1 class="display-3">Registrace -  konference 2020</h1>

            <form action="registrace"  method="post">
                <div class = "form-group ">
                    <label> Username </label>
                    <input type="text" name="user" class="form-control" required>
                </div>
                <div class="form-group">
                    <label> Password </label>
                    <input type="password" name="password" class="form-control" required>
                </div>
                <div class="form-group">
                    <label> Zadej heslo znovu: </label>
                    <input type="password" name="password2" class="form-control" required>
                </div>

                <button type="submit" class="btn btn-primary" name="reg_user"> Register </button>
            </form>
        </div>
    </div>
</div>