<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="<?php echo $popis; ?>">
    <meta name="keywords" content="<?php echo $klicova_slova; ?>">
    <title><?php echo $titulek; ?></title>

    <link href="/css/rezervace.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<body>

<nav class="navbar sticky-top navbar-expand-md bg-dark navbar-dark">
    <?php
    $menu = new JmenoMenu();
    $menu->jmenoMenu();

    ?>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="uvod">Úvod </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="program">Program</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="misto-konani">Místo konání</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="ubytovani">Ubytovani</a>
            </li>

            <?php
            $panel = new AdminPanel();
            $panel->adminPanel();
            ?>
        </ul>

        <ul class = "navbar-nav ">
            <li class="nav-item">
                <?php
                $inout = new INOUT();
                $inout->inOut();

                ?>
            </li>
        </ul>
    </div>
</nav>

<br>
<div class="container">
    <?php
    if(isset($_SESSION['msg'])) {
        echo '<div class="alert alert-primary text-center" role="alert">' . $_SESSION['msg'] . '</div>';
        unset($_SESSION['msg']);
    }
    ?>
</div>
<?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony ?>

<div class="container">
    <div class="row">
        <div class="col-md-4 text-justify ">
            <h2>Konference</h2>
            <p> Konference zaměřená na přípravu na distanční výuku </p>
        </div>

        <div class="col-md-4 text-justify">
            <h2>Adresa</h2>
            <p> Univerzitní 2732/8, 301 00 Plzeň 3 </p>
        </div>

        <div class="col-md-4 text-justify">
            <h2>Organizátoři</h2>
            <p> Ing. Marek V. ,
                Ing Jan J. ,
                Ing. Michal D. </p>
        </div>
    </div>
    <hr>
    <footer>
        <p>Michal Dvořák &copy;  2020 </p>
    </footer>
</div>

</body>
</html>
